production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: wb_parser_production
  pool: 5
  username: parser_mysql_user
  password: supersecretpassword

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: wb_parser_development
  pool: 5
  username: parser_mysql_user
  password: supersecretpassword

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: wb_parser_test
  pool: 5
  username: wb_parser_user
  password: supersecretpassword
